# Dockerfile.dev
FROM node:20-alpine
WORKDIR /app

# copia lock + package para cache estable
COPY package*.json ./
RUN npm install   # usa install porque el lock puede estar desactualizado durante la migración

# copia el resto del código
COPY . .

# (opcional) usuario no-root
# RUN adduser -D appuser && chown -R appuser:appuser /app
# USER appuser

EXPOSE 5173
CMD ["npm","run","dev","--","--host"]