ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS rut INTEGER;
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS dv VARCHAR(255);
ALTER TABLE funcionarios ADD COLUMN IF NOT EXISTS email VARCHAR(255);
